#! /bin/bash

test_option=cache-misses,LLC-loads,LLC-store-misses,LLC-load-misses,L1-dcache-load-misses,cache-references,cycles,instructions

perf stat -r 5 -e $test_option  ./compare 0
perf stat -r 5 -e $test_option  ./compare 1
perf stat -r 5 -e $test_option  ./compare 3
perf stat -r 5 -e $test_option  ./compare 4

